### ISSUE TITLE
[mtt] Failed osu-micro-benchmarks-5.6.2/mpi/one-sided/osu_put_bibw on host

### ISSUE THREAD

**Issue by avildema** [openucx/ucc#245]
Configuration
```
OMPI: 5.0.0a1
MOFED: MLNX_OFED_LINUX-5.1-2.5.8.0
Module: none
Test module: none
Nodes: jazz x6 (ppn=28(x6), nodelist=jazz[06,08,11,16,25,32])
```
 
MTT log:
http://hpcweb.lab.mtl.com/hpc/mtr_scrap/users/mtt/scratch/ucc/20210705_042928_99018_46207_jazz06.swx.labs.mlnx/html/test_stdout_7HNGrU.txt
 
Cmd:
`/hpc/mtr_scrap/users/mtt/scratch/ucc/20210705_042928_99018_46207_jazz06.swx.labs.mlnx/ompi_src/install/bin/mpirun -np 2 --display map --mca coll_ucc_enable 1 --mca coll_ucc_priority 100 --map-by node --bind-to core /hpc/mtr_scrap/users/mtt/scratch/ucc/20210705_042928_99018_46207_jazz06.swx.labs.mlnx/installs/6uoo/tests/osu_micro_benchmark/osu-micro-benchmarks-5.6.2/mpi/one-sided/osu_put_bibw`
 
Output:
```sh
=============================================================
# OSU MPI_Put Bi-directional Bandwidth Test v5.6.2
# Window creation: MPI_Win_allocate
# Synchronization: MPI_Win_post/start/complete/wait
# Size      Bandwidth (MB/s)[jazz06.swx.labs.mlnx:154306] ../../../../opal/mca/common/ucx/common_ucx_wpool.h:526  Error: ucp_atomic_cswap64 failed: -1
[jazz06:00000] *** An error occurred in MPI_Win_post
[jazz06:00000] *** reported by process [2164850689,0]
[jazz06:00000] *** on win ucx window 3
[jazz06:00000] *** MPI_ERR_OTHER: known error not in list
[jazz06:00000] *** MPI_ERRORS_ARE_FATAL (processes in this win will now abort,
[jazz06:00000] ***    and MPI will try to terminate your MPI job as well)+ rc=16
```

**Comment by vspetrov** [comment]
not related to UCC
