### ISSUE TITLE
[JENKINS] UCC unit tests breaks the CI system

### ISSUE THREAD

**Issue by artemry-nv** [openucx/ucc#253]
It looks like UCC unit tests break the CI cluster: during the final phase of testing it hangs and the overall system becomes non-operable (only hard reset helps). The tests were temporarily disabled. Look like a regression (found a UCC git commit without such issue).

**Comment by artemry-nv** [comment]
CC @vspetrov

**Comment by vspetrov** [comment]
the issue is caused by the known problem with gdr driver. currently this is worked around by setting the corresponding UCX var to disable GDR inside gtest.
