### ISSUE TITLE
Road map for a release

### ISSUE THREAD

**Issue by supunkamburugamuve** [openucx/ucc#263]
We implemented a UCX based transport for the Cylon project which is a distributed DataFrame. We are looking forward to integrating the collective communications with the Cylon project. Are you planning to release the UCC sometime soon? Is it released separately or along with UCX?

**Comment by vspetrov** [comment]
@supunkamburugamuve hi, thanks for the interest in the project.
the roadmap for release is: https://github.com/manjugv/ucc_wg_public/blob/6346dc1d221f74fd422d072fe8f58420c699de75/slides/ucc_release_roadmap_25june2021.pdf

Shortly, the v1.0 release is expected at Nov 2021. @manjugv

**Comment by supunkamburugamuve** [comment]
@vspetrov thanks for the information. Could I use it now without depending on a release?

**Comment by vspetrov** [comment]
Of course. Keep in mind though that "master" branch currently is subject to rapid changes including API (e.g. #259 ).
