### ISSUE TITLE
how to get ucc initialized with mt support 

### ISSUE THREAD

**Issue by TunchinKao** [openucx/ucc#305]
I was running the command in ` run_tests_torch_ucc.sh`
```
echo "INFO: UCC barrier (CPU)"
/bin/bash ${SRC_DIR}/test/start_test.sh ${SRC_DIR}/test/torch_barrier_test.py --backend=gloo
````

And encounter this error
```
[E torch_ucc_comm.cpp:156] ucc library wasn't initialized with mt support check ucc compile options 
```
What does this "mt" mean? Does it mean "multi-thread"? I guess.

But I can't find compile options regarding multithread mode.
Thank you.

**Comment by Sergei-Lebedev** [comment]
most likely ucx wasn't compiled with multithread support, check that you have --enable-mt in ucx configure cmd line
