### ISSUE TITLE
[mtt][atest] Fail test

### ISSUE THREAD

**Issue by avildema** [openucx/ucc#366]
Test: ucc-ompi.*;atest;atest

Configuration
```
OMPI: v5.0.0rc2
MOFED: MLNX_OFED_LINUX-5.4-1.0.3.0
Module: none
Test module: none
Nodes: jazz x2 (ppn=28(x2), nodelist=jazz[18,24])
```
 
MTT log:

http://hpcweb.lab.mtl.com//hpc/mtr_scrap/users/mtt/scratch/ucc/20211207_012044_191759_83678_jazz18.swx.labs.mlnx/html/test_stdout_aivlfY.txt 

Cmd:
`/hpc/mtr_scrap/users/mtt/scratch/ucc/20211207_012044_191759_83678_jazz18.swx.labs.mlnx/ompi_src/install/bin/mpirun -np 56 --display map --mca coll_ucc_enable 1 --mca coll_ucc_priority 100 --map-by node --bind-to core --mca pmix_server_max_wait 8 /hpc/mtr_scrap/users/mtt/scratch/ucc/20211207_012044_191759_83678_jazz18.swx.labs.mlnx/installs/YsHX/tests/atest/mtt-tests.git/atest/src/atest --time 0 -v 1 --test-cross 0`
 
Output:
```sh
Total tests:                    817
Total tests exec time (secs):   64
Total failed:                   1
Total success:                  816
```

comment:
one test of 10 fail

**Comment by avildema** [comment]
not help
https://github.com/openucx/ucc/issues/244#issuecomment-906180390

**Comment by vspetrov** [comment]
no longer reproduced
