### ISSUE TITLE
What CUDA versions are supported?

### ISSUE THREAD

**Issue by zasdfgbnm** [openucx/ucc#370]
Hi, I am trying to build UCC on PyTorch's CI, and it failed on the CUDA 10.2 CI because `__double2half` is added in CUDA 11. I will NOT request UCC to support CUDA 10.2, because PyTorch is already working on dropping CUDA 10.2 support as well.

But I searched this repository, and I didn't see any mention of versioning. The CI seems to be testing only one CUDA version as well. I really hope that UCC can clearly mention what is the lowest supported CUDA version on `README.md` and have a CI running on that CUDA version.

**Comment by manjugv** [comment]
@zasdfgbnm Thanks for posting this issue. We discussed this today in the WG and we will add the required documentation.

**Comment by zasdfgbnm** [comment]
Thanks a lot!
