### ISSUE TITLE
Getting Started with NCCL

### ISSUE THREAD

**Issue by esaliya** [openucx/ucc#377]
I am trying to test UCC with NCCL backend. Is there any documentation to get started?

**Comment by vspetrov** [comment]
Hi, there is not much specific documentation on NCCL (documentation covers UCC API in general).
TL/NCCL is available when UCC was compiled with nccl support (--with-cuda --with-nccl). If so, NCCL TL would be selected automatically for GPU based collectives. The selection can be altered using "-x UCC_TL_NCCL_TUNE= " parameter ,described here: 
https://github.com/openucx/ucc/wiki/FAQ#6-what-is-tl-scoring-and-how-to-select-a-certain-tl
