### ISSUE TITLE
TL/CUDA: what behavior if we cannot use cache?

### ISSUE THREAD

**Issue by kingchc** [openucx/ucc#438]
In `ucc_tl_cuda_create_cache`, it is possible `ucs_pgtable_init` return error. refer to
https://github.com/openucx/ucc/blob/4f0ad005468bc4f32bc225513102d24f800e4762/src/components/tl/cuda/tl_cuda_cache.c#L82-L86

In this case, what error code we should return (or just `UCC_OK` to proceed silently?)? and can I safely assume that TL/CUDA still works without cache (i.e., expected worse perf)?

Asking because I got compilation error (using clang) along this
```
tl_cuda_cache.c:82:9: error: variable 'status' is used uninitialized whenever 'if' condition is true [-Werror,-Wsometimes-uninitialized]
    if (UCS_OK != ucs_pgtable_init(&cache_desc->pgtable,
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
tl_cuda_cache.c:101:12: note: uninitialized use occurs here
    return status;
           ^~~~~~
tl_cuda_cache.c:82:5: note: remove the 'if' if its condition is always false
    if (UCS_OK != ucs_pgtable_init(&cache_desc->pgtable,
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
tl_cuda_cache.c:65:5: note: variable 'status' is declared here
    ucc_status_t status;
    ^
1 error generated.
```

cc @Sergei-Lebedev @vspetrov @bureddy

**Comment by Sergei-Lebedev** [comment]
Hi @kingchc,
It's a bug, because in case of error the return status is not properly initialized.
In general TL CUDA might work without cache, but it's a compile time option that we use mostly for debug purposes and perf without cache is noticeably worse.
