### ISSUE TITLE
Update the component diagram

### ISSUE THREAD

**Issue by manjugv** [openucx/ucc#532]
[ucc_components_v4.pdf](https://github.com/openucx/ucc/files/8827757/ucc_components_v4.pdf)

**Comment by manjugv** [comment]
@vspetrov @Sergei-Lebedev @bureddy Let me know, if the diagram has any missing elements?

**Comment by Sergei-Lebedev** [comment]
> @vspetrov @Sergei-Lebedev @bureddy Let me know, if the diagram has any missing elements?

TL MLX5 is missing, though it has not been merged yet

**Comment by Sergei-Lebedev** [comment]
Also TL Self is coming soon, but not sure we should mention it here. Also Vendor TL
