### ISSUE TITLE
Uninitialized global_config when loading tlcp components

### ISSUE THREAD

**Issue by BrodyWilliams** [openucx/ucc#627]
ucc_components_load() fails with tlcp components  because global_config.component_path is not set before the tl_ucp_iface_init constructor is called.

**Comment by vspetrov** [comment]
@BrodyWilliams could you share the backtrace ? I don't quite understand the flow. tl_ucp_iface_init constructor should be called when ucc_tl_ucp.so is being loaded. But that is supposed to happen from ucc_constructor -> ucc_components_load("tl", ...) when the path must be initialized properly.

**Comment by gvallee** [comment]
@vspetrov as far as i remember, there is no backtrace, it does not create a segfault. But the plugins end up not being selected at all.

**Comment by BrodyWilliams** [comment]
@vspetrov @gvallee - If I remember correctly, the master branch does seg fault. Our older UCC fork did not. I am traveling at the moment and can’t grab the backtrace but I think it was occurring on the strlen() call here: https://github.com/openucx/ucc/blob/master/src/utils/ucc_component.c#L131-L132

On Sep 20, 2022, at 12:27 PM, Geoffroy Vallee ***@***.******@***.***>> wrote:



@vspetrov<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fvspetrov&data=05%7C01%7Cbrodyw%40nvidia.com%7C1c1254a052ce49319be508da9b24fbfe%7C43083d15727340c1b7db39efd9ccc17a%7C0%7C0%7C637992880394707278%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=TZgwG%2BNNapr%2BiiofZvGrskOnE5pjGY7sT%2FO33f7zoKk%3D&reserved=0> as far as i remember, there is no backtrace, it does not create a segfault. But the plugins end up not being selected at all.

**Comment by BrodyWilliams** [comment]
Problem has been resolved by changes to plugin and/or commit since ucc fork. Closing.
