### ISSUE TITLE
[RFE] EC/CUDA: mode to avoid using persistent kernel

### ISSUE THREAD

**Issue by marsaev** [openucx/ucc#673]
Currently triggered_post for `EE CUDA STREAM` launches persistent kernel that orchestrates the collective. 

There are some usecases which i think can allow avoid using launching kernel - popular usecase is trying to overlap `cublasGemm` and some collective, i.e. `bcast` - cublas populates all SM resources available and there is no room for any kernels to start, including UCC persistent kernel. 

However, for UCP TL and collectives like `bcast`, `gatherv` or even `alltoallv` copy engines can be utilized (even if it would be slower than smcopy, but user might have to opt-in to enable this mode). Together with something like https://github.com/openucx/ucc/issues/672 it might be possible to cover such usecases.

**Comment by Sergei-Lebedev** [comment]
persistent wait operation using cudaMemOps was implemented and released as part of UCC v1.3
