### ISSUE TITLE
Version 1.2.0 Release (April 30th)

### ISSUE THREAD

**Issue by manjugv** [openucx/ucc#714]

**Comment by marsaev** [comment]
@manjugv , is there official 1.2.0 release? I don't see it here https://github.com/openucx/ucc/releases or in tags, but i already see bump to 1.3 lined up: https://github.com/openucx/ucc/pull/782

**Comment by manjugv** [comment]
Yes, it is an official release candidate.

**Comment by marsaev** [comment]
I see `1.2.0-rc1` tag was just released - https://github.com/openucx/ucc/releases, thanks! I was just worried 1.2.0 will be skipped all together :)
