### ISSUE TITLE
Updating ucc.conf usages in Wiki->FAQ

### ISSUE THREAD

**Issue by shimmybalsam** [openucx/ucc#726]
Hi @manjugv @Sergei-Lebedev please review this new suggested version of section 13. UCC configuration file and priority. Attached here:
[ucc_configurable_updated.md](https://github.com/openucx/ucc/files/10675315/ucc_configurable_updated.md)

The main additions regard tuning sections per architecture and defukat usage or non usage for hpcx users vs users who close UCC repo and use locally.

**Comment by manjugv** [comment]
@shimmybalsam I have added the content with minor changes (https://github.com/openucx/ucc/wiki/FAQ#13-ucc-configuration-file-and-priority), please feel free to tell me or @Sergei-Lebedev , if you need any changes.

**Comment by shimmybalsam** [comment]
@manjugv thanks looks great! 
Two comments 

1.  You added this sentence twice once at the begining and once at the end:
"The UCC configuration file (ucc.conf) provides a unified way of tailoring the behavior of UCC components - CLs, TLs, and ECs. The configuration file can contain any UCC variables of the format VAR = VALUE"

I assume this can be removed from the end?

2. Should we add a line explaining that users can also add more architecture tunings and create a PR with researched data proof and then we can combine into the defualt ucc.conf?

**Comment by manjugv** [comment]
@shimmybalsam 

1. It is not a redundant sentence, however, I agree it can be written better. It is updated now, please check.
2. This is obvious and there is no need to specify it, IMO.

**Comment by shimmybalsam** [comment]
> @shimmybalsam
> 
> 1. It is not a redundant sentence, however, I agree it can be written better. It is updated now, please check.
> 2. This is obvious and there is no need to specify it, IMO.

@manjugv OK, looks good! I will close the issue.
