### ISSUE TITLE
[Question] Relationship between CLs and TLs

### ISSUE THREAD

**Issue by anxietymonger** [openucx/ucc#817]
https://github.com/openucx/ucc/blob/6bdb758bc3d7467a29fc86f9cc80dc636c8ae82c/docs/user_guide.md?plain=1#L67

In the description above, it says that TLs are composed by CLs. However, in the architecture chart in main README, CLs are on the top of TLs, which is seemingly the opposite of the description.

I'm new to UCC and it may be a stupid question, but could anyone help me understand what is going on here?

**Comment by Sergei-Lebedev** [comment]
Hi @anxietymonger, sorry for the late answer. Right, I think wording is not correct here, it should be CLs are composed by TLs.
CC @manjugv

**Comment by anxietymonger** [comment]
Thank you for your answer! Close the issue.
