### ISSUE TITLE
make install failed

### ISSUE THREAD

**Issue by pangjuan8848** [openucx/ucc#853]
make[3]: Leaving directory '/root/mspangj/ucc-1.2.0/src/components/mc/cpu'
make[2]: Leaving directory '/root/mspangj/ucc-1.2.0/src/components/mc/cpu'
Making install in components/mc/rocm
make[2]: Entering directory '/root/mspangj/ucc-1.2.0/src/components/mc/rocm'
  CC       libucc_mc_rocm_la-mc_rocm.lo
In file included from /root/mspangj/ucc-1.2.0/src/utils/arch/rocm_def.h:16:0,
                 from mc_rocm.h:14,
                 from mc_rocm.c:8:
/opt/rocm/hip/include/hip/hip_runtime_api.h:333:2: error: #error ("Must define exactly one of __HIP_PLATFORM_HCC__ or __HIP_PLATFORM_NVCC__");
 #error("Must define exactly one of __HIP_PLATFORM_HCC__ or __HIP_PLATFORM_NVCC__");
  ^~~~~
In file included from mc_rocm.h:16:0,
                 from mc_rocm.c:8:
/opt/rocm/hip/include/hip/hip_complex.h:33:2: error: #error ("Must define exactly one of __HIP_PLATFORM_HCC__ or __HIP_PLATFORM_NVCC__");
 #error("Must define exactly one of __HIP_PLATFORM_HCC__ or __HIP_PLATFORM_NVCC__");
  ^~~~~
In file included from mc_rocm.c:8:0:
mc_rocm.h:33:51: error: unknown type name ‘hipStream_t’; did you mean ‘hipError_t’?
                                                   hipStream_t stream);
                                                   ^~~~~~~~~~~
                                                   hipError_t
mc_rocm.h:44:5: error: unknown type name ‘hipStream_t’
     hipStream_t                    stream;
     ^~~~~~~~~~~
In file included from mc_rocm.c:11:0:
/opt/rocm/hip/include/hip/hip_runtime.h:60:2: error: #error ("Must define exactly one of __HIP_PLATFORM_HCC__ or __HIP_PLATFORM_NVCC__");
 #error("Must define exactly one of __HIP_PLATFORM_HCC__ or __HIP_PLATFORM_NVCC__");
  ^~~~~
In file included from /opt/rocm/hip/include/hip/hip_runtime.h:65:0,

**Comment by Sergei-Lebedev** [comment]
@edgargabriel could you please have a look

**Comment by edgargabriel** [comment]
@pangjuan8848 what ROCm version are you using? HIP_PLATFORM_HCC has been replaced by HIP_PLATFORM_AMD quite a while back, so updating the ROCm version on your system should resolve the issue

**Comment by edgargabriel** [comment]
@pangjuan8848 the check for ROCm 5.0 is there because the organization of the header files changed between ROCm 4.x and 5.x. However, the first version that we ever tested UCC on was ROCM 4.5, and I would definitely not expect it to work with anything older than that. If you do an update, I would recommend to take one of the ROCm 5.x releases

**Comment by pangjuan8848** [comment]
@edgargabriel OK，thank you very much for your answer,i will try later
