### ISSUE TITLE
1.3.0 release tag

### ISSUE THREAD

**Issue by zzzoom** [openucx/ucc#965]
While updating the UCC spack package with 1.3.0 I noticed that our URL for releases didn't work anymore, because 1.3.0's tag has switched from `v1.2.0` (old style) to `v.1.3.0`. Will future releases keep the dot after `v`?

**Comment by manjugv** [comment]
We will keep the old v1.3.0 style.

**Comment by zzzoom** [comment]
Got it, thanks @manjugv
