### ISSUE TITLE
API/ABI compatibility of UCC

### ISSUE THREAD

**Issue by jakirkham** [openucx/ucc#968]
What sort of API/ABI compatibility does UCC provide?

IOW if another library is built against a particular version of UCC (like 1.1.0), what versions of UCC could it work with at runtime?

Looking at this code, it appears that it might be [SemVer]( https://semver.org ). Is that true or is there some other compatibility guarantees?

https://github.com/openucx/ucc/blob/20eae37090a4ce1b32bcce6144ccad0b49943e0b/src/core/ucc_lib.c#L319-L328

**Comment by Sergei-Lebedev** [comment]
Hi @jakirkham, UCC is API and ABI backward compatible within the same major version. At the same time UCC relies on UCS (one of the UCX components) and UCS is not backward compatible.

**Comment by jakirkham** [comment]
Thanks Sergey! 🙏

**Comment by Sergei-Lebedev** [comment]
> Reopening to ask a follow up question
> 
> > At the same time UCC relies on UCS (one of the UCX components) and UCS is not backward compatible.
> 
> Does UCC plan to move off UCS to UCP (backwards compatible) in the future?

It's not about replacing UCP with UCS. UCP is an API for point to point communication, we have TL UCP in UCC that implements collectives on top of UCP. UCS is a service library that has implementations of different data structures and algorithms (such as list, queue, parser, registration cache ...).  We have plans to replace some of the UCS functionality by reimplementing it inside UCC, but not all of it.
